import test from 'node:test';
import assert from 'node:assert/strict';
const base = 'http://127.0.0.1:18777';
const html = await (await fetch(base)).text();
const token = html.match(/name="client-token" content="([^"]+)"/)[1];
const headers = { 'X-Client-Token': token, 'Content-Type': 'application/json' };
const get = route => fetch(base + route, {headers});
const post = (route, data, extra={}) => fetch(base + route, {method:'POST',headers:{...headers,...extra},body:JSON.stringify(data)});
test('本地服务已就绪',async()=>{const r=await get('/health');assert.equal((await r.json()).ready,true)});
test('敏感接口要求本机会话',async()=>{assert.equal((await fetch(base+'/api/state')).status,403)});
test('跨站请求不能控制工作台',async()=>{assert.equal((await post('/api/project/create',{name:'Forbidden'},{Origin:'https://example.com'})).status,403)});
test('POST 需要正确校验头',async()=>{assert.equal((await post('/api/project/create',{name:'Forbidden'},{'X-Client-Token':'invalid'})).status,403)});
test('未知对话不会返回历史记录',async()=>{const r=await get('/api/history?id=not-owned');assert.equal(r.status,400);const body=await r.json();assert.match(body.error,/暂未同步/);assert.equal(body.thread,undefined)});
test('不会对不存在的对话发起修改',async()=>{const r=await post('/api/turn/start',{threadId:'not-owned',text:'never run'});assert.equal(r.status,400)});
test('同名项目被拒绝而不创建副本',async()=>{const s=await (await get('/api/state')).json();const r=await post('/api/project/create',{name:s.projects[0].name});assert.equal(r.status,400);assert.match((await r.json()).error,/同名/)});
test('GET 无法调用工作台修改接口',async()=>{assert.equal((await get('/studio/mode?editing=false')).status,404)});
test('只接受图片附件',async()=>{assert.equal((await post('/api/upload',{data:'data:text/html;base64,PHNjcmlwdD4='})).status,400)});
test('静态服务不会暴露源码或父目录',async()=>{assert.equal((await get('/server.mjs')).status,404);assert.equal((await get('/%2e%2e/workspace.json')).status,404)});
test('预览脚本通过桥接代理读取资源',async()=>{const r=await get('/studio/web');const body=await r.text();assert.match(body,/\/studio\/preview.js/);assert.doesNotMatch(body,/token=([a-f0-9]{32,})/)});
test('已连接的模型和原生画面可读取',async()=>{const c=await(await get('/api/codex')).json();assert.equal(c.loggedIn,true);assert.ok(c.models.length);const frame=await get('/api/frame');assert.equal(frame.headers.get('content-type'),'image/png');assert.ok((await frame.arrayBuffer()).byteLength>1000)});
