import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const c=vm.createContext({});vm.runInContext(fs.readFileSync(new URL('../engine/Shared/engine.js',import.meta.url),'utf8'),c);const E=c.StudioEngine;
const make=()=>({entry:'a',state:{active:true},viewport:{width:300,height:600},assets:[{name:'wood',id:'wood.png'}],actions:{},pages:{a:{root:{id:'a',type:'container',children:[{id:'p',type:'image',asset:'wood',style:{width:100,height:160}}]},presentation:{when:{get:'state.active'},rules:[{match:{asset:'wood'},set:{offsetX:25,offsetY:-30,opacity:.7},badge:{text:'8.5'}}]}},b:{root:{id:'b',type:'container',children:[]}}}});
test('presentation follows manual nested and imported positions without mutating overrides',()=>{
 const m=make(),s=E.initial(m),o={'a/p':{patch:{x:64,y:80,rotation:17}}},adds={a:[{id:'copy',parent:'a',type:'image',asset:'wood.png',x:20,y:35,width:80,height:120,rotation:-10}]},before=JSON.stringify({o,adds});const p=E.compose(m,s,o,adds);
 assert.equal(p.nodes.find(n=>n.id==='a/p').x,89);assert.equal(p.nodes.find(n=>n.id==='copy').y,5);assert.equal(p.nodes.find(n=>n.id==='copy#badge').rotation,-10);assert.equal(JSON.stringify({o,adds}),before);
 s.editingPage='a';const edit=E.compose(m,s,o,adds);assert.equal(edit.nodes.find(n=>n.id==='copy').y,35);assert.equal(edit.nodes.some(n=>n.id.includes('#badge')),false);
});
test('runtime fallback is used only if the author has no real layer of that ID',()=>{const m=make();m.pages.a.presentation.fallbacks=[{id:'new',asset:'wood',x:10,y:20,width:60,height:90}];let s=E.initial(m);const source=E.frame(m,s);assert.equal(source.nodes.filter(n=>n.id==='new').length,1);assert.equal(source.nodes.find(n=>n.id==='new').x,35);const p=E.compose(m,s,{}, {a:[{id:'new',asset:'wood.png',type:'image',x:100,y:20,width:60,height:90}]});assert.equal(p.nodes.filter(n=>n.id==='new').length,1);assert.equal(p.nodes.find(n=>n.id==='new').x,125)});
test('scoped delays cancel on navigation and recursive calls are bounded',()=>{const m=make();m.actions={start:[{type:'delay',duration:1,scope:'page',actions:[{type:'set',path:'active',value:false}]}],loop:[{type:'call',action:'loop'}]};let s=E.reduce(m,E.initial(m),{action:'start'});const id=Object.keys(s.pendingEffects)[0];s=E.reduce(m,s,{type:'navigate',page:'b'});s=E.reduce(m,s,{type:'effectComplete',id});assert.equal(s.state.active,true);assert.throws(()=>E.reduce(m,s,{action:'loop'}),/256 steps/)});
test('invalid analysis cannot invoke score logic',()=>{const m=make();m.actions.done=[{type:'set',path:'active',value:false}];for(const value of [null,{}, {version:1,regions:[]},{version:1,regions:Array(12).fill({coverage:1.1,saturation:0})}])assert.throws(()=>E.reduce(m,E.initial(m),{requiresAnalysis:true,action:'done',value}),/Invalid model analysis/)});
