import * as T from './model-vendor/three.module.js';
import {GLTFLoader} from './model-vendor/GLTFLoader.js';
// A generic HTML model layer. Editor transforms stay owned by the workbench.
const SIZE=1024, instances=new Set();
if(typeof originalFetch==='function'){const hostFetch=window.fetch;window.fetch=(input,options)=>input instanceof Request&&input.url.startsWith('blob:')?originalFetch(input,options):hostFetch(input,options)}
// Use the existing authenticated event transport, including the desktop proxy.
async function stored(key,value,knownRevision){const project=key.split(':')[0];const token=new URLSearchParams(location.search).get('token')||'';const response=await fetch('/event',{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':token},body:JSON.stringify({projectID:project,side:'web',event:{type:'modelPaintStorage',method:value===undefined?'GET':'POST',key,value,knownRevision}})});const result=await response.json();if(!response.ok||result?.error)throw Error(result.error||'Storage unavailable');return result}
function encodePixels(bytes){const c=document.createElement('canvas');c.width=c.height=SIZE;c.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(bytes),SIZE,SIZE),0,0);return c.toDataURL('image/png').split(',')[1]}
async function decodePixels(png){const image=new Image();image.src='data:image/png;base64,'+png;await image.decode();const c=document.createElement('canvas');c.width=c.height=SIZE;c.getContext('2d').drawImage(image,0,0);return new Uint8Array(c.getContext('2d').getImageData(0,0,SIZE,SIZE).data)}
function target(size=SIZE){return new T.WebGLRenderTarget(size,size,{depthBuffer:true,minFilter:T.LinearFilter,magFilter:T.LinearFilter})}
const vertex=`varying vec2 tex; varying vec4 projected; uniform mat4 sourceWorld; uniform mat4 viewProjection;
void main(){tex=uv;projected=viewProjection*sourceWorld*vec4(position,1.);gl_Position=vec4(uv*2.-1.,0.,1.);}`;
const fragment=`#include <packing>
varying vec2 tex; varying vec4 projected; uniform sampler2D previous; uniform sampler2D depthMap; uniform vec2 brush; uniform vec2 viewport; uniform float radius; uniform float strength; uniform vec3 ink;
void main(){vec4 old=texture2D(previous,tex);vec3 p=projected.xyz/projected.w;vec2 screen=p.xy*.5+.5;float depth=unpackRGBAToDepth(texture2D(depthMap,screen));float dist=length((screen-brush)*viewport);float mask=(1.-smoothstep(radius*.8,radius,dist))*strength;
if(projected.w<=0.||p.z*.5+.5>depth+.00002||screen.x<0.||screen.y<0.||screen.x>1.||screen.y>1.)mask=0.;gl_FragColor=vec4(mix(old.rgb,ink,mask),1.);}`;
export class ModelPaint {
 constructor(host,options){this.host=host;this.options=options;this.dead=false;this.ready=false;this.editing=true;this.undo=[];this.redo=[];this.meshes=[];this.probes=[];this.pointers=new Map();this.lastCommand=null;this.busy=false;this.remoteRevision="";this.pendingWrites=0;this.writeChain=Promise.resolve();
  this.renderer=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.setClearColor(0,0);this.canvas=this.renderer.domElement;this.canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;touch-action:none';host.replaceChildren(this.canvas);
  for(const [left,top] of [[0,0],[100,0],[0,100]]){const p=document.createElement('span');p.style.cssText=`position:absolute;left:${left}%;top:${top}%;width:0;height:0;pointer-events:none`;host.append(p);this.probes.push(p)}
  this.message=document.createElement('div');this.message.style.cssText='position:absolute;left:4px;right:4px;bottom:4px;font:12px sans-serif;text-align:center;pointer-events:none;color:#082db5';host.append(this.message);
  this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(35,1,.01,50);this.camera.position.set(0,1.1,3.7);this.camera.lookAt(0,0,0);this.scene.add(new T.HemisphereLight(0xffffff,0x877861,2.2));const light=new T.DirectionalLight(0xffffff,2);light.position.set(2,3,4);this.scene.add(light);
  this.a=target();this.b=target();this.depth=target(1024);this.depthMaterial=new T.MeshDepthMaterial({depthPacking:T.RGBADepthPacking,side:T.DoubleSide});this.uvScene=new T.Scene();this.uvCamera=new T.Camera();this.clearTargets();
  this.down=e=>this.pointerDown(e);this.move=e=>this.pointerMove(e);this.up=e=>this.pointerUp(e);this.wheel=e=>{if(this.editing||!this.ready)return;e.preventDefault();e.stopPropagation();this.camera.position.multiplyScalar(Math.exp(Math.max(-100,Math.min(100,e.deltaY))*.003));this.camera.position.clampLength(1.7,8);this.draw()};
  this.canvas.addEventListener('pointerdown',this.down);this.canvas.addEventListener('pointermove',this.move);this.canvas.addEventListener('pointerup',this.up);this.canvas.addEventListener('pointercancel',this.up);this.canvas.addEventListener('wheel',this.wheel,{passive:false});
  this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);instances.add(this);this.status('Loading model…');this.syncTimer=setInterval(()=>this.syncPainting(),2000);
 }
 status(en,zh){this.message.textContent=this.options.locale==='zh-Hans'?(zh||en):en}
 clearTargets(){const r=this.renderer;r.setClearColor(0xffffff,1);for(const t of [this.a,this.b]){r.setRenderTarget(t);r.clear()}r.setRenderTarget(null);r.setClearColor(0,0)}
 async load(url,key){this.key=key;try{const rawFetch=typeof originalFetch==='function'?originalFetch:fetch;const response=await rawFetch(url);if(!response.ok)throw Error('Model download failed');const gltf=await new GLTFLoader().parseAsync(await response.arrayBuffer(),location.origin+'/');if(this.dead){gltf.scene.traverse(n=>n.geometry?.dispose());return}this.object=gltf.scene;this.object.updateMatrixWorld(true);let box=new T.Box3().setFromObject(this.object),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3());this.object.position.sub(center);const group=new T.Group();group.add(this.object);group.scale.setScalar(1.8/Math.max(size.x,size.y,size.z));this.object=group;this.scene.add(group);this.scene.updateMatrixWorld(true);
   group.traverse(m=>{if(!m.isMesh)return;if(!m.geometry.attributes.uv)throw Error('Model has no UV');if(Array.isArray(m.material))throw Error('Multiple materials are not supported yet');const original=m.material;const mat=new T.MeshStandardMaterial({map:this.a.texture,roughness:.65,metalness:0,side:T.DoubleSide,normalMap:original.normalMap});m.material=mat;this.meshes.push(m);
    const u={previous:{value:this.a.texture},depthMap:{value:this.depth.texture},brush:{value:new T.Vector2()},viewport:{value:new T.Vector2()},radius:{value:12},strength:{value:1},ink:{value:new T.Vector3()},sourceWorld:{value:m.matrixWorld.clone()},viewProjection:{value:new T.Matrix4()}};
    const painter=new T.Mesh(m.geometry,new T.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,uniforms:u,side:T.DoubleSide,depthTest:false,depthWrite:false}));painter.frustumCulled=false;painter.userData.source=m;this.uvScene.add(painter);
    for(const v of Object.values(original))if(v?.isTexture&&v!==original.normalMap)v.dispose();original.dispose();
   });const record=await stored(key);if(record?.png){this.remoteRevision=record.revision||"";const bytes=await decodePixels(record.png);if(bytes.length!==SIZE*SIZE*4)throw Error('Invalid saved texture');this.restore(bytes)}this.ready=true;this.status('','');this.resize();this.host.dataset.modelReady='true';
  }catch(e){this.status('Model unavailable: '+e.message,'模型加载失败：'+e.message);this.host.dataset.modelError=e.message;throw e}}
 update(n,editing){this.n=n;this.editing=editing;this.canvas.style.pointerEvents=editing?'none':'auto';this.canvas.style.touchAction=editing?'auto':'none';this.resize();const cmd=n.paintOptions?.command;if(this.lastCommand===null)this.lastCommand=cmd?.seq||0;else if(cmd&&cmd.seq!==this.lastCommand&&this.ready&&!editing){this.lastCommand=cmd.seq;if(n.paintCommandOwner!=='ios')this.command(cmd.type)} }
 local(x,y){const p=this.probes.map(e=>e.getBoundingClientRect());const ax=p[1].x-p[0].x,ay=p[1].y-p[0].y,bx=p[2].x-p[0].x,by=p[2].y-p[0].y,det=ax*by-ay*bx;if(Math.abs(det)<.001)return null;return {x:((x-p[0].x)*by-(y-p[0].y)*bx)/det,y:((y-p[0].y)*ax-(x-p[0].x)*ay)/det}}
 resize(){if(this.dead)return;const w=Math.max(1,this.host.clientWidth),h=Math.max(1,this.host.clientHeight);if(this.w!==w||this.h!==h){this.w=w;this.h=h;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.depth.setSize(Math.min(1024,w*2),Math.min(1024,h*2))}this.draw()}
 draw(){if(this.dead)return;this.renderer.setRenderTarget(null);this.renderer.render(this.scene,this.camera)}
 snapshot(){const data=new Uint8Array(SIZE*SIZE*4);this.renderer.readRenderTargetPixels(this.a,0,0,SIZE,SIZE,data);return data}
 checkpoint(){this.undo.push(this.snapshot());if(this.undo.length>12)this.undo.shift();this.redo=[]}
 restore(bytes){const texture=new T.DataTexture(bytes,SIZE,SIZE,T.RGBAFormat);texture.needsUpdate=true;const scene=new T.Scene(),material=new T.MeshBasicMaterial({map:texture,depthTest:false,depthWrite:false});scene.add(new T.Mesh(new T.PlaneGeometry(2,2),material));this.renderer.setRenderTarget(this.a);this.renderer.render(scene,new T.Camera());texture.dispose();material.dispose();scene.children[0].geometry.dispose();this.draw()}
 pointerDown(e){if(this.editing||!this.ready||this.busy)return;e.stopPropagation();e.preventDefault();this.canvas.setPointerCapture(e.pointerId);const p=this.local(e.clientX,e.clientY);if(!p)return;this.pointers.set(e.pointerId,p);if(this.pointers.size===1){this.last=p;if((this.n.paintOptions?.mode||0)!==1){this.checkpoint();this.stamp(p)}}else this.last=null}
 pointerMove(e){if(!this.pointers.has(e.pointerId)||this.editing)return;e.stopPropagation();e.preventDefault();const p=this.local(e.clientX,e.clientY);if(!p)return;const old=this.pointers.get(e.pointerId);this.pointers.set(e.pointerId,p);const mode=this.n.paintOptions?.mode||0;
  if(mode===1||this.pointers.size>1){this.object.rotation.y+=(p.x-old.x)*4;this.object.rotation.x=Math.max(-1.3,Math.min(1.3,this.object.rotation.x+(p.y-old.y)*3));this.draw();return}
  const last=this.last||p,dx=(p.x-last.x)*this.w,dy=(p.y-last.y)*this.h,steps=Math.min(32,Math.max(1,Math.ceil(Math.hypot(dx,dy)/Math.max(2,(this.n.paintOptions?.size||12)*.35))));for(let i=1;i<=steps;i++)this.stamp({x:last.x+(p.x-last.x)*i/steps,y:last.y+(p.y-last.y)*i/steps});this.last=p;
 }
 pointerUp(e){if(!this.pointers.has(e.pointerId))return;e.stopPropagation();this.pointers.delete(e.pointerId);this.last=null;if(this.ready)this.saveDraft();}
 async syncPainting(){if(!this.ready||this.dead||this.busy||this.pendingWrites||this.pointers.size||document.hidden)return;try{const record=await stored(this.key,undefined,this.remoteRevision);if(this.dead||this.busy||this.pendingWrites||this.pointers.size||!record?.png)return;const bytes=await decodePixels(record.png);if(this.dead||this.pendingWrites||this.pointers.size)return;this.remoteRevision=record.revision||'';this.restore(bytes)}catch(e){this.status('Sync failed: '+e.message)}}
 write(key,value){this.pendingWrites++;const next=this.writeChain.catch(()=>{}).then(()=>stored(key,value));this.writeChain=next.finally(()=>this.pendingWrites--);return this.writeChain}
 async saveDraft(){try{await this.write(this.key,{png:encodePixels(this.snapshot()),model:this.options.asset,version:1})}catch(e){if(!this.dead)this.status('Draft save failed: '+e.message,'草稿保存失败：'+e.message)}}
 stamp(p){this.scene.updateMatrixWorld(true);this.camera.updateMatrixWorld(true);const r=this.renderer;this.scene.overrideMaterial=this.depthMaterial;r.setRenderTarget(this.depth);r.setClearColor(0xffffff,1);r.clear();r.render(this.scene,this.camera);this.scene.overrideMaterial=null;
  const options=this.n.paintOptions||{},color=/^#[0-9a-f]{6}$/i.test(options.color||'')?options.color:'#082db5',ink=new T.Color(options.mode===2?'#ffffff':color); // Convert sRGB UI input to linear target pixels.
  for(const m of this.uvScene.children){const u=m.material.uniforms;u.previous.value=this.a.texture;u.brush.value.set(p.x,1-p.y);u.viewport.value.set(this.w,this.h);u.radius.value=Math.max(1,Math.min(60,Number(options.size)||12));u.strength.value=Math.max(.01,Math.min(1,Number(options.opacity)||1));u.ink.value.set(ink.r,ink.g,ink.b);u.sourceWorld.value.copy(m.userData.source.matrixWorld);u.viewProjection.value.multiplyMatrices(this.camera.projectionMatrix,this.camera.matrixWorldInverse)}
  r.setRenderTarget(this.b);r.clear();r.render(this.uvScene,this.uvCamera);[this.a,this.b]=[this.b,this.a];for(const m of this.meshes)m.material.map=this.a.texture;r.setClearColor(0,0);this.draw();this.host.dataset.paintDirty='true';
 }
 async command(type){if(this.busy)return;try{if(type==='undo'&&this.undo.length){this.redo.push(this.snapshot());this.restore(this.undo.pop())}else if(type==='redo'&&this.redo.length){this.undo.push(this.snapshot());this.restore(this.redo.pop())}else if(type==='clear'){this.checkpoint();this.clearTargets();this.draw()}else if(type==='save'){this.busy=true;this.status('Saving…','保存中…');const id=crypto.randomUUID(),png=encodePixels(this.snapshot());await this.write(this.options.project+':'+id,{png,model:this.options.asset,version:1});await this.write(this.key,{png,model:this.options.asset,version:1});if(!this.dead){this.status('Saved','已保存');this.host.dataset.paintDirty='false';this.options.onSave(id)}}if(type!=='save')await this.saveDraft();}catch(e){this.status('Save failed: '+e.message,'保存失败：'+e.message)}finally{this.busy=false}}
 dispose(){if(this.dead)return;this.dead=true;clearInterval(this.syncTimer);instances.delete(this);this.observer.disconnect();for(const m of this.meshes){m.geometry.dispose();m.material.normalMap?.dispose();m.material.dispose()}for(const m of this.uvScene.children)m.material.dispose();this.a.dispose();this.b.dispose();this.depth.dispose();this.depthMaterial.dispose();this.renderer.dispose();this.renderer.forceContextLoss();this.undo=[];this.redo=[]}
}
new MutationObserver(()=>{for(const i of instances)if(!i.host.isConnected)i.dispose()}).observe(document.documentElement,{childList:true,subtree:true});
