export function installAnnotation({nativeHost,nativeMessage,toast,icons,getAttachment,commit}){
 const toolbar=document.createElement('div');toolbar.className='annotation-toolbar';toolbar.setAttribute('role','toolbar');toolbar.setAttribute('aria-label','截图与图片标注');
 const tools=[['select','mouse-pointer-2','选择标注'],['crop','scan','框选截图'],['rect','square','方框标注'],['ellipse','circle','圆形标注'],['arrow','move-up-right','箭头标注'],['pen','pencil','画笔标注'],['text','type','文字标注']];
 toolbar.innerHTML=tools.map(([id,icon,label])=>`<button type="button" class="icon-btn" data-mark-tool="${id}" aria-label="${label}" title="${label}"><i data-lucide="${icon}"></i></button>`).join('')+'<button type="button" class="icon-btn" id="annotation-open" aria-label="编辑图片" title="打开图片进行标注"><i data-lucide="image-plus"></i></button>';
 document.querySelector('.topbar-center').append(toolbar);
 const overlay=document.createElement('section');overlay.id='annotation-overlay';overlay.className='hidden';overlay.setAttribute('aria-label','图片标注编辑器');
 overlay.innerHTML='<div class="annotation-controls"><span id="annotation-hint">拖动框选要发送的区域</span><label title="标注颜色">颜色<input id="annotation-color" type="color" value="#ff3b30" aria-label="标注颜色"></label><label>粗细<select id="annotation-width" aria-label="画笔粗细"><option value="3">细</option><option value="6" selected>中</option><option value="10">粗</option></select></label><button type="button" class="icon-btn" id="annotation-undo" aria-label="撤销标注" title="撤销"><i data-lucide="undo-2"></i></button><button type="button" class="icon-btn" id="annotation-redo" aria-label="重做标注" title="重做"><i data-lucide="redo-2"></i></button><button type="button" class="icon-btn" id="annotation-delete" aria-label="删除选中标注" title="删除选中标注（Delete）"><i data-lucide="trash-2"></i></button><button type="button" class="subtle" id="annotation-full">恢复整图</button><button type="button" class="secondary" id="annotation-cancel">取消</button><button type="button" class="primary" id="annotation-done">添加到对话</button></div><div class="annotation-stage"><canvas id="annotation-canvas" tabindex="0" aria-label="标注画布"></canvas><input id="annotation-text" class="hidden" placeholder="输入标注文字，Enter 确认" aria-label="标注文字"></div>';
 document.body.append(overlay);const fileInput=document.createElement('input');fileInput.type='file';fileInput.accept='image/png,image/jpeg,image/webp';fileInput.hidden=true;document.body.append(fileInput);
 const $=id=>document.getElementById(id),canvas=$('annotation-canvas'),ctx=canvas.getContext('2d'),stage=overlay.querySelector('.annotation-stage');
 let selected=-1,history=[];let inlineCapture=false;let image=null,tool='crop',marks=[],redo=[],crop=null,drag=null,draft=null,editingId=null,capturing=false,textPoint=null,previousFocus=null;
 const width=()=>Number($('annotation-width').value),color=()=>$('annotation-color').value;
 const bounds=(a,b)=>({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)});
 function select(next){finishText();tool=next;canvas.style.cursor=tool==='select'?'default':'crosshair';toolbar.querySelectorAll('[data-mark-tool]').forEach(b=>{b.classList.toggle('selected',window.annotationActive&&b.dataset.markTool===tool);b.setAttribute('aria-pressed',String(!!window.annotationActive&&b.dataset.markTool===tool))});$('annotation-hint').textContent=tool==='crop'?'拖动框选截图范围；留空则发送整图':tool==='text'?'点击图片添加文字；Enter 确认':'在图片上拖动标注，完成后添加到对话';}
 function drawMark(context,m){context.save();context.strokeStyle=m.color;context.fillStyle=m.color;context.lineWidth=m.width;context.lineCap='round';context.lineJoin='round';const r=m.b?bounds(m.a,m.b):null;context.beginPath();
  if(m.type==='rect')context.strokeRect(r.x,r.y,r.w,r.h);
  if(m.type==='ellipse'){context.ellipse(r.x+r.w/2,r.y+r.h/2,r.w/2,r.h/2,0,0,Math.PI*2);context.stroke()}
  if(m.type==='arrow'){context.moveTo(m.a.x,m.a.y);context.lineTo(m.b.x,m.b.y);const angle=Math.atan2(m.b.y-m.a.y,m.b.x-m.a.x),head=Math.max(16,m.width*4);context.moveTo(m.b.x-head*Math.cos(angle-.5),m.b.y-head*Math.sin(angle-.5));context.lineTo(m.b.x,m.b.y);context.lineTo(m.b.x-head*Math.cos(angle+.5),m.b.y-head*Math.sin(angle+.5));context.stroke()}
  if(m.type==='pen'){m.points.forEach((p,i)=>i?context.lineTo(p.x,p.y):context.moveTo(p.x,p.y));context.stroke()}
  if(m.type==='text'){context.font=`600 ${Math.max(22,m.width*6)}px -apple-system, sans-serif`;context.textBaseline='top';context.fillText(m.text,m.a.x,m.a.y)}context.restore();
 }
 function draw(){if(!image)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0);marks.filter(m=>m.type!=='crop').forEach(m=>drawMark(ctx,m));if(draft&&draft.type!=='crop')drawMark(ctx,draft);const area=draft?.type==='crop'?bounds(draft.a,draft.b):crop;
  if(area){ctx.save();ctx.fillStyle='#17212b80';ctx.beginPath();ctx.rect(0,0,canvas.width,canvas.height);ctx.rect(area.x,area.y,area.w,area.h);ctx.fill('evenodd');ctx.strokeStyle='#12bd7b';ctx.lineWidth=3;ctx.strokeRect(area.x,area.y,area.w,area.h);ctx.restore()}
  const chosen=marks[selected];if(chosen&&chosen.type!=='crop'&&!drag){const r=markBounds(chosen),scale=canvas.width/canvas.getBoundingClientRect().width,pad=5*scale;ctx.save();ctx.strokeStyle='#2676e8';ctx.lineWidth=scale;ctx.setLineDash([4*scale,3*scale]);ctx.strokeRect(r.x-pad,r.y-pad,r.w+pad*2,r.h+pad*2);ctx.setLineDash([]);ctx.fillStyle='white';for(const x of [r.x-pad,r.x+r.w+pad])for(const y of [r.y-pad,r.y+r.h+pad]){ctx.fillRect(x-3*scale,y-3*scale,6*scale,6*scale);ctx.strokeRect(x-3*scale,y-3*scale,6*scale,6*scale)}ctx.restore()}
  $('annotation-delete').disabled=selected<0||!marks[selected];canvas.setAttribute('aria-description',selected>=0?'已选中标注 '+(selected+1)+'，按 Delete 删除':'未选中标注');
  $('annotation-undo').disabled=!history.length;$('annotation-redo').disabled=!redo.length;
 }
 function fit(){if(!image)return;const area=document.querySelector('.canvas-layout').getBoundingClientRect();Object.assign(overlay.style,{left:area.left+'px',top:area.top+'px',width:area.width+'px',height:area.height+'px'});const scale=Math.min((area.width-(inlineCapture?0:24))/image.width,(area.height-(inlineCapture?0:24))/image.height);canvas.style.width=Math.max(1,image.width*scale)+'px';canvas.style.height=Math.max(1,image.height*scale)+'px';}
 function restoreCrop(){crop=[...marks].reverse().find(m=>m.type==='crop')?.area||null}
 function save(){history.push([...marks]);redo=[]}
 function push(mark){save();marks.push(mark);selected=marks.length-1;restoreCrop();draw()}
 function removeSelected(){if(selected<0||!marks[selected])return;save();marks.splice(selected,1);selected=-1;restoreCrop();draw()}
 function markBounds(m){if(m.type==='text'){ctx.font=`600 ${Math.max(22,m.width*6)}px -apple-system, sans-serif`;return {x:m.a.x,y:m.a.y,w:ctx.measureText(m.text).width,h:Math.max(22,m.width*6)}}if(m.type==='pen'){const xs=m.points.map(p=>p.x),ys=m.points.map(p=>p.y);return {x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}return bounds(m.a,m.b)}
 function hit(p){const tolerance=8*canvas.width/canvas.getBoundingClientRect().width;return marks.findLastIndex(m=>{if(m.type==='crop')return false;const r=markBounds(m),inside=p.x>=r.x-tolerance&&p.x<=r.x+r.w+tolerance&&p.y>=r.y-tolerance&&p.y<=r.y+r.h+tolerance;if(m.type==='rect'&&tool!=='select')return inside&&Math.min(Math.abs(p.x-r.x),Math.abs(p.x-r.x-r.w),Math.abs(p.y-r.y),Math.abs(p.y-r.y-r.h))<=tolerance;return inside})}
 function point(event){const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(event.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(event.clientY-r.top)*canvas.height/r.height))}}
 function finishText(){if(!textPoint)return;const text=$('annotation-text').value.trim();if(text)push({type:'text',a:textPoint,text,color:color(),width:width()});textPoint=null;$('annotation-text').classList.add('hidden');$('annotation-text').value=''}
 function end(){window.annotationActive=false;document.body.classList.remove('annotating');window.getSelection()?.removeAllRanges();overlay.classList.add('hidden');$('annotation-text').classList.add('hidden');textPoint=null;image=null;marks=[];redo=[];draft=null;drag=null;select(tool);window.reportNativeLayout?.();previousFocus?.focus?.()}
 async function load(url,id=null,inPlace=false){inlineCapture=inPlace;finishText();const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('无法读取图片'));img.src=url});if(img.width*img.height>32000000)throw new Error('图片过大，请选择小于 3200 万像素的图片');previousFocus=document.activeElement;image=img;editingId=id;marks=[];redo=[];history=[];selected=-1;crop=null;canvas.width=img.width;canvas.height=img.height;window.annotationActive=true;document.body.classList.add('annotating');window.getSelection()?.removeAllRanges();overlay.classList.remove('hidden');select(tool);fit();draw();window.reportNativeLayout?.()}
 async function start(next){if(capturing)return;if(window.annotationActive){select(next);return}tool=next;capturing=true;try{if(nativeHost){const data=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{window.receiveAnnotationCapture=null;reject(new Error('截图超时，请重试'))},10000);window.receiveAnnotationCapture=value=>{clearTimeout(timeout);window.receiveAnnotationCapture=null;value?resolve(value):reject(new Error('请先打开手机预览，或选择“编辑图片”'))};nativeMessage({action:'captureAnnotation'})});await load(data,null,true)}else{const response=await fetch('/api/frame');if(!response.ok)throw new Error('未连接手机预览，请选择编辑图片');const url=URL.createObjectURL(await response.blob());try{await load(url)}finally{URL.revokeObjectURL(url)}}}catch(error){toast(error.message,true)}finally{capturing=false}}
 toolbar.querySelectorAll('[data-mark-tool]').forEach(b=>b.onclick=()=>start(b.dataset.markTool));$('annotation-open').onclick=()=>fileInput.click();fileInput.onchange=async()=>{const file=fileInput.files[0];fileInput.value='';if(!file)return;const url=URL.createObjectURL(file);try{tool='rect';await load(url)}catch(e){toast(e.message,true)}finally{URL.revokeObjectURL(url)}};
 window.editWorkbenchAttachment=async id=>{const a=getAttachment(id);if(!a)return;try{tool='rect';await load(a.preview,id)}catch(e){toast(e.message,true)}};
 canvas.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();window.getSelection()?.removeAllRanges();canvas.focus({preventScroll:true});finishText();const p=point(e);const found=hit(p);if(found>=0||tool==='select'){selected=found;draw();return}selected=-1;if(tool==='text'){textPoint=p;const r=canvas.getBoundingClientRect(),s=stage.getBoundingClientRect(),input=$('annotation-text');input.style.left=Math.min(r.left-s.left+p.x*r.width/canvas.width,stage.clientWidth-270)+'px';input.style.top=Math.min(r.top-s.top+p.y*r.height/canvas.height,stage.clientHeight-46)+'px';input.classList.remove('hidden');input.focus();return}canvas.setPointerCapture(e.pointerId);drag=p;draft={type:tool,a:p,b:p,points:[p],color:color(),width:width()};draw()};
 canvas.onpointermove=e=>{if(!drag)return;e.preventDefault();draft.b=point(e);draft.points.push(draft.b);draw()};
 canvas.onpointerup=e=>{if(!drag)return;draft.b=point(e);if(draft.type==='crop'){const area=bounds(draft.a,draft.b);if(area.w>=8&&area.h>=8)push({type:'crop',area})}else if(draft.type==='pen'?draft.points.length>1:Math.hypot(draft.b.x-draft.a.x,draft.b.y-draft.a.y)>3)push(draft);drag=null;draft=null;draw()};canvas.onpointercancel=()=>{drag=null;draft=null;draw()};
 $('annotation-text').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();finishText()}if(e.key==='Escape'){textPoint=null;$('annotation-text').value='';$('annotation-text').classList.add('hidden');e.stopPropagation()}};
 $('annotation-undo').onclick=()=>{finishText();if(history.length){redo.push([...marks]);marks=history.pop();selected=marks.length-1}restoreCrop();draw()};$('annotation-redo').onclick=()=>{if(redo.length){history.push([...marks]);marks=redo.pop();selected=marks.length-1}restoreCrop();draw()};$('annotation-delete').onclick=removeSelected;$('annotation-full').onclick=()=>push({type:'crop',area:null});$('annotation-cancel').onclick=end;
 $('annotation-done').onclick=async()=>{finishText();const button=$('annotation-done');button.disabled=true;try{const output=document.createElement('canvas'),area=crop||{x:0,y:0,w:image.width,h:image.height};output.width=Math.max(1,Math.round(area.w));output.height=Math.max(1,Math.round(area.h));const c=output.getContext('2d');c.translate(-area.x,-area.y);c.drawImage(image,0,0);marks.filter(m=>m.type!=='crop').forEach(m=>drawMark(c,m));const blob=await new Promise(resolve=>output.toBlob(resolve,'image/png'));if(!blob)throw new Error('图片导出失败');await commit(blob,editingId);end();document.getElementById('prompt').focus()}catch(e){toast(e.message,true)}finally{button.disabled=false}};
 document.addEventListener('keydown',e=>{if(!window.annotationActive)return;if(e.target.closest?.('input,textarea,select,[contenteditable=true]'))return;if((e.key==='Backspace'||e.key==='Delete')&&!e.metaKey&&!e.ctrlKey&&!e.altKey){e.preventDefault();e.stopPropagation();removeSelected();return}if(e.key==='Escape'&&e.target!==$('annotation-text')){e.preventDefault();end()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'&&e.target!==$('annotation-text')){e.preventDefault();$(e.shiftKey?'annotation-redo':'annotation-undo').click()}});new ResizeObserver(fit).observe(document.querySelector('.canvas-layout'));addEventListener('resize',fit);window.cancelWorkbenchAnnotation=()=>{if(window.annotationActive)end()};icons();
}
